site_name: Weifund
repo_url: https://github.com/weifund/weifund-dapp-basic
site_description: Weifund Documentation
theme: readthedocs
extra_css: [extra.css]
pages:
- Introduction: 'index.md'
- Campaigns:
  - Contribute: 'campaigns/contributing.md'
  - Run A Campaign: 'campaigns/running.md'
- Contract Details: 'contracts.md'
- Contributing to Weifund: 'contributing/github.md'
- Community: 'community/team_community.md'
- Policies:
  - Terms of Use: 'policy/policies.md'
  - Privacy Policy: 'policy/privacy_policy.md'
  - License: 'policy/license.md'
- Glossary: 'glossary.md'
